package com.tefper.daas.parque.util;

public enum ProductType {

	BALNEARIO("BALNEARIO"),

	MOVISTAR_TV_TDP_HOGAR_DIGITAL("MOVISTAR TV TDP HOGAR DIGITAL"),

	INTERMEDIO_SATELITAL("INTERMEDIO SATELITAL"),

	CONTROL_SATELITAL("CONTROL SATELITAL"),

	MOVISTAR_TV_BASICO_SAT_TDP("MOVISTAR TV BASICO SAT TDP"),

	LINEA_TELEFONICA_VOIP("LINEA TELEFONICA VOIP"),

	INTERMEDIO_SATELITAL_TDP("INTERMEDIO SATELITAL TDP"),

	ESTANDAR_DIGITAL_FTTH("ESTANDAR DIGITAL FTTH"),

	MOVISTAR_UNO_DUO("MOVISTAR UNO - DUO"),

	MOVISTAR_TV_HOGAR_DIGITAL("MOVISTAR TV HOGAR DIGITAL"),

	DUO_NAKED_TV_ESTANDAR_INTE("DUO NAKED - TV ESTANDAR + INTE"),

	SPEEDY_MONO_HFC("SPEEDY MONO HFC"),

	ESTANDAR_TRIO_TDP("ESTANDAR TRIO TDP"),

	ESTANDAR_FULL("ESTANDAR FULL"),

	DUO_NAKED_SOLO_INTERNET("DUO NAKED - SOLO INTERNET"),

	MOVISTAR_UNO_TRIO("MOVISTAR UNO - TRIO"),

	ESTANDAR("ESTANDAR"),

	INTERNET_NAKED_FTTH("INTERNET NAKED FTTH"),

	MOVISTAR_ESTANDAR_SATELITAL("MOVISTAR ESTANDAR SATELITAL"),

	ESTANDAR_TDP_DIGITAL("ESTANDAR TDP DIGITAL"),

	ESTELAR_DIGITAL("ESTELAR DIGITAL"),

	ESTELAR_TRIO_TDP("ESTELAR TRIO TDP"),

	INTERMEDIO("INTERMEDIO"),

	BALNEARIO_SATELITAL("BALNEARIO SATELITAL"),

	ESTELAR_TDP_DIGITAL("ESTELAR TDP DIGITAL"),

	ESTELAR_SATELITAL_TDP("ESTELAR SATELITAL TDP"),

	ESTELAR("ESTELAR"),

	STD_DIG_MOVISTAR_UNO_TRIO("STD DIG MOVISTAR UNO - TRIO"),

	ESTANDAR_SATELITAL("ESTANDAR SATELITAL"),

	OTROS("Otros"),

	MOBILE("MOBILE");

	private String value;

	ProductType(String value) {
		this.value = value;
	}

	public String toString() {
		return String.valueOf(value);
	}

	public static ProductType fromValue(String text) {
		for (ProductType b : ProductType.values()) {
			if (String.valueOf(b.value).equals(text)) {
				return b;
			}
		}
		return null;
	}
}
